#!/usr/bin/env bash

package=${PWD##*/};
# bats cache --clear-cache
rm -rf build/;
rm *.zip;
brazil-build;
bats transform -x AWSLambda-1.0 -t $package-1.0 -p $package-1.0;
unzip *.zip -d build
\ls src/ | xargs -n1 -I{} bash -c 'rm -fr build/{}; ln -hfs $PWD/src/{}/ $PWD/build/';
