#!/bin/bash

source ~/.scripts/cdk-functions
echo "Stack from CDK-Functions $STACK";
echo "Starting Brazil Recursive Build";

brazil ws clean;
pass "Brazil Clean complete";

brazil ws sync --md;
pass "Brazil WS Sync Complete"

brazil-recursive-cmd --allPackages brazil-build || warn "Failed to complete Build" exit 1;
pass "Finishing Brazil Recursive Build";

STACK=$1;
if [[ -n $STACK && $STACK == '--bootstrap' ]]; then
    shift;
    echo "This deployment will boostrap the account";
    STACK="BONESBootstrap-${USER}-${REGION}-${CDK_DEFAULT_ACCOUNT}-${REGION}";
    pass "Boostrap Stack: $STACK";
    brazil-build cdk bootstrap;
    brazil-build cdk bootstrap "aws://${CDK_DEFAULT_ACCOUNT}/${REGION}"
    brazil-build bootstrap;
    brazil-build cdk deploy $STACK;
    STACK='.';
fi
if [[ -n $STACK && $STACK == '--pipeline' ]]; then
    pipeline_name="${USER}-${REGION}-${PWD##*/}"
    pipeline_name="${STACK%%CDK}"
    echo "This deployment will deploy only the pipeline to pipelines.amazon.com/pipeline/${pipeline_name}";
    STACK="BONESBootstrap-${USER}-${REGION}-${CDK_DEFAULT_ACCOUNT}-${REGION}";
    pass "Pipeline Stack: $STACK";
    brazil-build deploy:pipeline;
    brazil-build cdk deploy "${pipeline_name}/PDGScaffoldingStack"
    brazil-build cdk deploy "${pipeline_name}/PipelineDeploymentStack"
    exit 0;
fi
if [[ -n $STACK && $STACK == '.' ]]; then
    STACK="${USER}-${REGION}-${PWD##*/}"
    STACK="${STACK%%CDK}"
fi

if [[ -n $STACK ]]; then
    shift;
    #echo "Deploying Assets";
    pass "Using $STACK";
    #brazil-build deploy:assets $STACK; # CLI Utility for deploy CDK Assets (Brazil or local Assets) to Deployment Bucket for a particular Stack
    echo "Deploying CDK Stacks";
    echo "using params $@"
    # TODO Add --hotswap flag
    brazil-build cdk deploy -v --debug --require-approval never --progress bar --toolkit-stack-name CDKToolkit-v2 $@ $STACK; # CLI Utility for deploying CDK Stack
else
    #echo "Deploying Assets *";
    warn "Operating on all Stacks in CDK";
    warn "This is may not the intended behavior;"
    #ls build/cdk.out/ | awk -F . "/template.json/{print $STACK}" | cut -f 1 -d '.' | xargs -n1 brazil-build deploy:assets;
    echo "Deploying CDK Stacks *";
    brazil-build cdk deploy -v --debug --all --require-approval never --progress bar --toolkit-stack-name CDKToolkit-v2;
fi

#console-access; # Utility for opening AWS console

echo "Finished Deployment";

cdk-full-delete "$STACK"; # Utility for deleting failed stacks
