#!/bin/bash

if [[ "$#" -gt 1 ]] ; then
  echo "Usage: $0 <account> "
  exit 1
fi

if [[ -z $1 || ! $1 =~ ^[0-9]*$ ]]; then
    echo "Using Personal Account";
    accountId=$CDK_PERSONAL_ACCOUNT_ID
else
    accountId=$1
    shift;
fi

echo "Getting Console for $accountId";

curl --location-trusted -c ~/.midway/cookie -b ~/.midway/cookie -X GET -H "Accept: application/json" -d '{"awsAccountId":"'"$accountId"'", "awsPartition": "aws", "policyArns":["arn:aws:iam::aws:policy/AdministratorAccess"], "sessionDuration": 43200}' https://iibs-midway.corp.amazon.com/GetConsoleAccessUrl | jq '.url' | xargs /usr/bin/open -a "/Applications/Google Chrome.app"
