#!/bin/bash

git status;
pwd;
upgrade() {
    grep "$1" ./Config | grep -v "$2";
    sed -i '' -E -e "s/($1.*)=.*;/\1= $2;/g" Config;
}
remove() {
    sed -i '' -e '/$1\s/d' Config;
    echo "Remember to run:";
    echo "";
    echo "    brazil vs removemajorversions -vs $vs -mv $1-<major-version>";
    echo "";
    echo "You can find matching versions at:";
    echo "";
    echo "    https://code.amazon.com/version-sets/$vs?show_packages=yes#packages";
    echo "";
}
replace() {
    sed -i '' -e 's/$1[^-].*;/$2=$3;/' Config;
    echo "Remember to run:";
    echo "";
    echo "    brazil vs removemajorversions -vs $vs -mv $1-<major-version>";
    echo "";
    echo "You can find matching versions at:";
    echo "";
    echo "    https://code.amazon.com/version-sets/$vs?show_packages=yes#packages";
    echo "";
}

month=$(date +%m);
year=$(date +%y);

git checkout -b "ailor/SAS-$month-$year";
prep-cr "SAS-$month-$year" -v -v -v --no-format -i -i -m "Remove SAS Risks from the Config file
    upgrade SlimCat 8.5.0;
    upgrade Jackson-core 2.12.x;
    upgrade Jackson-databind 2.12.x ;
    replace Jackson Jackson-core 2.12.x ;
    upgrade OpenJDK8 1.1;
    upgrade NimbusJOSEJWT 9.x_internal;
" $@;
