git submodule add https://github.com/cheat/cheatsheets.git ./.config/cheat/cheatsheets/community
git submodule add https://github.com/tokorom/completor-shell.git ./.vim/bundle/completor-shell
git submodule add https://github.com/Shougo/neocomplete.vim.git ./.vim/bundle/neocomplete.vim
git submodule add https://github.com/terryma/vim-multiple-cursors.git ./.vim/bundle/vim-multiple-cursors
git submodule add https://github.com/vim-syntastic/syntastic.git ./.vim/bundle/syntastic
git submodule add https://github.com/itchyny/lightline.vim.git ./.vim/bundle/lightline.vim
git submodule add https://github.com/dhruvasagar/vim-table-mode.git ./.vim/bundle/vim-table-mode
git submodule add https://github.com/editorconfig/editorconfig-vim.git ./.vim/bundle/editorconfig-vim
git submodule add https://github.com/mxw/vim-jsx.git ./.vim/bundle/vim-jsx
git submodule add https://github.com/Shougo/neoinclude.vim.git ./.vim/bundle/neoinclude.vim
git submodule add https://github.com/tpope/vim-fugitive.git ./.vim/bundle/vim-fugitive
git submodule add https://github.com/maralla/completor.vim.git ./.vim/bundle/completor.vim
git submodule add https://github.com/tpope/vim-pathogen.git ./.vim/bundle/vim-pathogen
git submodule add https://github.com/scrooloose/nerdtree.git ./.vim/bundle/nerdtree
git submodule add https://github.com/maralla/completor-neosnippet.git ./.vim/bundle/completor-neosnippet
git submodule add https://github.com/pre-commit/pre-commit-hooks ./.cache/pre-commit/repotyf1_j6k
git submodule add https://github.com/pre-commit/pre-commit-hooks ./.cache/pre-commit/repocdtpke0b
git submodule add https://github.com/pre-commit/mirrors-fixmyjs ./.cache/pre-commit/repon6lpmxtw
git submodule add https://github.com/pre-commit/mirrors-fixmyjs ./.cache/pre-commit/repo521l5lrl
git submodule add https://github.com/crate-ci/typos ./.cache/pre-commit/repo_vb0scny
git submodule add https://github.com/pre-commit/mirrors-fixmyjs ./.cache/pre-commit/repogkrz05zf
git submodule add https://github.com/pre-commit/mirrors-fixmyjs ./.cache/pre-commit/repoyqpvhy9d
git submodule add https://github.com/crate-ci/typos ./.cache/pre-commit/repowm6xrdq0
