repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: pretty-format-json
- repo: https://github.com/crate-ci/typos
  rev: v1.1.9
  hooks:
  -   id: typos
- repo: https://github.com/pre-commit/mirrors-fixmyjs
  rev: v2.0.0
  hooks:
  -   id: fixmyjs
