#!/bin/sh
# Wait for wifi to be connected
while [[ `/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk '/ state/ {print substr($0, index($0, $2))}'` != 'running' ]];do
    sleep 1;
done
# Give time to finish connecting
sleep 45;

# Open Chrome links for Big Screen
#/usr/bin/osascript -e "tell application \"/Applications/Google Chrome.app\"" -e "make new window" -e "activate" -e "end tell"
/usr/bin/open -a "/Applications/Google Chrome.app" 'https://github.com/urbn/FPcom'
/usr/local/bin/fullscreen "Google Chrome" 0

# Open Chrome Dev Enviorment
/usr/bin/osascript -e "tell application \"/Applications/Google Chrome.app\"" -e "make new window" -e "activate" -e "end tell"
/usr/bin/open -a "/Applications/Google Chrome.app" 'http://localhost:3000'
/usr/local/bin/fullscreen "Google Chrome" 0

# Open Firefox Dev enviorment (Never works)
/usr/bin/open -a "/Applications/Firefox.app" 'http://localhost:3000'

# Open Safari Dev Enviorment
/usr/bin/open -a "/Applications/Safari.app" 'http://youtube.com'
#/usr/local/bin/fullscreen "Safari" 0

# Open Second Chrome window for small screen
/usr/bin/osascript -e "tell application \"/Applications/Google Chrome.app\"" -e "make new window" -e "activate" -e "end tell"
/usr/bin/open -a "/Applications/Google Chrome.app" 'http://amazon.com'
/usr/local/bin/fullscreen "Google Chrome" 0
/usr/local/bin/fullscreen "/Applicationss/Hyper.app" 0

# If not connected to work network, open the VPN Site
if [[ `/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk '/ SSID/ {print substr($0, index($0, $2))}'` != 'wpa2' ]]; then
    # Need to open Firefox in Dev enviorment
    /usr/local/bin/notify "Open All" "Opening a VPN connection since none appears to exist."
    vpn
fi

# Make Firefox Fullscreen.
#/usr/local/bin/fullscreen "Firefox" 0
