#!/bin/bash

ACCOUNT="145224550763";
REGION="us-west-2";
SERVICE="DeviceReturnsOrderService";
get-credentials "$ACCOUNT" "$REGION";

cluster=$(aws ecs list-clusters --region "$REGION" | jq -r '.clusterArns[]' | grep "$SERVICE");
echo "CLUSTER: $cluster";
service=$(aws ecs list-services --region "us-west-2" --cluster "$cluster" | jq -r '.serviceArns[0]');
echo "DNS: $dns";
echo "DNS: $dns";
echo "SERVICE: $service";
task=$(aws ecs list-tasks --cluster="$cluster" --region "$REGION" | jq -r ".taskArns [0]")
echo "TASK: $task";

aws ecs execute-command --interactive --cluster="$cluster" --region "$REGION" --container="Application" --command="/bin/sh" --task="$task";
