#!/bin/sh

# Checkout a new branch and bring the latest commit with you from that branch

pwd;
mainline="$(git current-branch)";
head="$(git rev-parse HEAD)";
echo "Creating branch $1 with commit $head";
git checkout -b "$1";
echo "Cherry Picking:"
git show -s --pretty=full "$head";
#git cherry-pick "$head";
git checkout "$mainline";
git reset --hard HEAD~;
git checkout "$1";
