#!/bin/sh

# run a git command in all subdirectories that are (likely) git repositories
# e.g:
# - git all status
# - git all fetch origin

for git_dir in */.git; do \
    work_tree=`dirname $git_dir`
    echo "\x1B[1m\x1B[36m$work_tree\x1B[0m"
    git --git-dir=$git_dir --work-tree=$work_tree "$@"
    echo "\x1B[1m\x1B[36m-------------------------------------\x1B[0m"
done
