#!/bin/sh

# run a git command in all subdirectories that are (likely) git repositories
# if we are not in a .git repo, then move up 1 directory.
# e.g:
# - git all status
# - git all fetch origin

if [ -d .git ]; then
    cd ..;
fi

# inside workspace
for git_dir in */.git; do \
    if [ -d $git_dir ]; then
        work_tree=`dirname $git_dir`
        echo "\x1B[1m\x1B[36m$work_tree\x1B[0m"
        if [ "$#" -gt 0 ]; then
            git --git-dir=$git_dir --work-tree=$work_tree "$@"
        fi
        echo "\x1B[1m\x1B[36m-------------------------------------\x1B[0m"
    fi
done

# multiple workspace directories
for src_dir in */src; do
    cd $src_dir;
    for git_dir in */.git; do
        if [ -d $git_dir ]; then
            work_tree=`dirname $git_dir`;
            echo "\x1B[1m\x1B[36m$work_tree\x1B[0m [$(pwd)/$work_tree]";
            if [ "$#" -gt 0 ]; then
                git --git-dir=$git_dir --work-tree=$work_tree "$@";
            fi
            echo "\x1B[1m\x1B[36m===================================================\x1B[0m";
        fi
    done
    cd ../../;
done
