#!/bin/bash

if [[ "$#" -lt 1 || "$#" -gt 3 ]] ; then
  echo "Usage: $0 <account> [<region>] [<secret-name]"
  exit 1
fi

if [[ -z $1 || ! $1 =~ ^[0-9]*$ ]]; then
    echo "Using Personal Account";
    accountId="$CDK_PERSONAL_ACCOUNT_ID";
else
    accountId="$1"
    shift;
fi

if [[ -z $1 || ! $1 =~ ^[a-z] ]]; then
    echo "Using Default Region";
    region="$REGION";
else
    region="$1";
    shift;
fi

if [[ -z $1 ]]; then
    echo "Using Default Secret Name";
    secretName="db-secret";
else
    secretName="$1";
    shift;
fi


# connecion string:
# mysql://<user>:<password>@vpce-0dff3957426c55a33-teq78l4k.vpce-svc-0cdbac1c293cbe664.eu-west-1.vpce.amazonaws.com:8192/kdmsdb
aws-credentials "$accountId" "$region";
dbSecret=$(aws --region "$region" secretsmanager list-secrets | jq -r '.SecretList[]|select(.Name|contains("'"$secretName"'"))|.Name' | xargs aws --region "$region" secretsmanager get-secret-value --query 'SecretString' --output text --secret-id | sed 's/\\"/"/g');
echo "$dbSecret" | jq
type1=$(echo "$dbSecret" | jq -r '{str: "\(.dbDriverClass)://\(.user):\(.password)@\(.dbUrl|split("//")|.[1])"} | .str');
type2=$(echo "$dbSecret" | jq -r '{str: "\(.engine)://\(.username):\(.password)@\(.host|split("//")|.[1])"} | .str');
echo "$type1";
echo "$type2";

if [[ -n "$type1" ]]; then
    echo "Using: $type1";
    mycli "$type1";
elif [[ -n "$type2" ]]; then
    echo "Using: $type2";
    mycli "$type2";
else
    echo "Both the urls types failed";
fi
