#!/bin/bash

title="$(icalBuddy -l1 1 -ea -nc -iep "title" eventsNow | sed 's/* //g' | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]')";
category="$3";

echo "Title:"
echo "$title"
if [[ -z "$title" ]]; then
    echo "No current meetings, please enter title:"
    read -r title;
fi

if [[ -z "$category" ]]; then
    echo "No category available, please enter category (blank for meeting)"
    read -r category;
fi
if [[ -z "$category" ]]; then
    category="meeting";
fi

echo "Hit enter to open: $title"
read -r CONFIRM
if [[ -z "$CONFIRM" ]]; then
    notes new "$category" "$title";
fi
