#!/bin/bash

note="$(echo "$3")";
if [[ -z "$note" ]]; then
    note="$(notes latest)";
elif [[ ! -f "$note" ]]; then
    note="$(notes ls | grep -i "$3" | head -n1)";
fi

echo "Hit enter to open: $note"

read -r CONFIRM

if [[ -z "$CONFIRM" ]]; then
    $EDITOR "$note";
fi
