#!/usr/bin/env python
import socket
import sys

HOST = ''
PORT = 5555

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
try:
    s.bind((HOST, PORT))
except socket.error as msg:
    sys.exit()
s.listen(10)
while 1:
    conn, addr = s.accept()
    print(addr)
    while 1:
        data = conn.recv(1024)
        if not data: break
        print(data)
    conn.close()
