#!/usr/bin/osascript
on run argv
    set done to 1
    tell application "Google Chrome"
        set window_list to every window # get the windows
        repeat with the_window in window_list # for every window
            set tab_list to every tab in the_window # get the tabs

            repeat with the_tab in tab_list # for every tab
                tell the_tab
                    set urlName to URL
                    if "127.0.0.1" is in urlName then
                        do shell script "echo " & "URL: " & (urlName as string) & "Success"
                        set done to 0
                        reload
                    else if "localhost" is in urlName then
                        do shell script "echo " & "URL: " & (urlName as string) & "Success"
                        set done to 0
                        reload
                    else
                        do shell script "echo " & "URL: " & (urlName as string)
                    end if
                end tell
            end repeat

        end repeat

    end tell
    return done
end run