#!/bin/bash

if [[ $1 -eq -1 ]]; then
    tabs=$(chrome-cli list tabs | tac);
elif [[ $1 -gt 0 ]]; then
    tabs=$(chrome-cli list tabs -w $1);
else
    tabs=$(chrome-cli list tabs -w $(chrome-cli list windows | head -n1 | awk -F'[][]' '{print $2}'));
fi

echo "Chrome Version:";
chrome-cli chrome version;
for tab in $tabs; do # Iterate tabs
    tabId=$(echo "$tab" | awk -F'[][]' '{print $2}');
    url=$(chrome-cli info -t "$tabId" | grep -o "^Url:.*" | cut -c 6-);
    title=$(chrome-cli info -t "$tabId" | grep -o "^Title:.*" | cut -c 8-);
    if [[ -z "$tabId" ]]; then # Ghost Tab
        continue;
    else #
        info=$(chrome-cli info -t "$tabId");
        if [[ -z "$info" ]]; then # Ghost Tab
            continue;
        else
            echo "$info";
        fi
        chrome-cli activate -t "$tabId";
        echo "Close (x), Kill (k), Save (s)";
        echo "Back (b), Forward (f)";
        echo "Bottom (B), Top (T), GoTo (g)";
        echo "Make Actionable (a), Reload (r)";
        echo "(q) to exit";
    fi #
    while true; do # Continue iterating the same tab
        echo "Enter to continue review";
        #chrome-cli info -t $tabId && exit 1
        read -r ACTION;
        if [[ "$ACTION" == "x" ]]; then # Close
            chrome-cli close -t "$tabId";
            break;
        elif [[ "$ACTION" == "r" ]]; then # Back
            chrome-cli reload -t "$tabId";
        elif [[ "$ACTION" == "g" ]]; then # Back
            chrome-cli activate -t "$tabId";
        elif [[ "$ACTION" == "B" ]]; then # Scroll Bottom
            chrome-cli reload -t "$tabId";
            echo "Wait 5 seconds to finish reload";
            sleep 5;
            chrome-cli execute 'window.scrollTo(0, document.body.scrollHeight);' -t "$tabId";
        elif [[ "ACTION" == "T" ]]; then # Scroll Top
            chrome-cli execute 'window.scrollTo(0, 0);' -t "$tabId";
        elif [[ "$ACTION" == "b" ]]; then # Back
            chrome-cli back -t "$tabId";
        elif [[ "$ACTION" == "a" ]]; then # Actinable
            task add "$title $url";
        elif [[ "$ACTION" == "f" ]]; then # Forward
            chrome-cli forward -t "$tabId";
        elif [[ "$ACTION" == "k" ]]; then # Kill
            echo "Kill Functionality not yet supported";
            break;
        elif [[ "$ACTION" == "s" ]]; then # Save
            echo "<DT><A HREF=\"$url\" ADD_DATE=\"$(date +%s)\">$title</A></DT>" >> ~/bookmarks.html;
            chrome-cli close -t "$tabId";
            break;
        elif [[ "$ACTION" == "q" ]]; then # Kill
            exit 0;
        else #
            break;
        fi #
    done #
done
