#!/bin/bash

if [[ $1 -eq -1 ]]; then
    tabs=$(chrome-cli list tabs | tac);
elif [[ $1 -gt 0 ]]; then
    tabs=$(chrome-cli list tabs -w $1);
else
    tabs=$(chrome-cli list tabs -w $(chrome-cli list windows | head -n1 | awk -F'[][]' '{print $2}'));
fi

echo "Chrome Version:";
chrome-cli chrome version;
#for tab in $tabs; do # Iterate tabs not working...?
while read tab; do
    tabId=$(echo "$tab" | awk -F'[][]' '{print $2}');
    url=$(chrome-cli info -t "$tabId" | grep -o "^Url:.*" | cut -c 6-);
    title=$(chrome-cli info -t "$tabId" | grep -o "^Title:.*" | cut -c 8-);
    if [[ -z "$tabId" ]]; then # Ghost Tab
        echo "Ghost Tab";
        continue;
    else #
        info=$(chrome-cli info -t "$tabId");
        if [[ -z "$info" ]]; then # Ghost Tab
            continue;
        else
            echo "$info";
        fi
        chrome-cli activate -t "$tabId";
        echo "activate";
        sleep 1;

        #chrome-cli reload -t "$tabId";
        #echo "reload";
        #sleep 10;

        echo "execute";
        chrome-cli execute 'window.location="https://code.amazon.com/permissions/show-group?utf8=%E2%9C%93&type=Person&group="+window.location.search.split("user=").pop();'
        echo "Loading new page from Query Selector";
        sleep 35;
        chrome-cli execute 'document.querySelector("body > div.container-fluid > div.row > div.col-lg-9.main > div.row > div:nth-child(1) > div:nth-child(1) > div.panel-body > ul").innerText' >> ~/all-creturns-packages.txt
        echo "wait";
        sleep 1;

        echo "close";
        chrome-cli close -t "$tabId";
        sleep 1;
    fi #
done <<< "$tabs";
