#!/bin/bash

gogpt "$@";
gum confirm "Continue to Google?" --default=false --affirmative "Next" --negative "Quit" || exit 0;
s -p "google" "$@";
gum confirm "Continue Stack Overflow?" --default=false --affirmative "Next" --negative "Quit" || exit 0;
s -p "stackoverflow" "$@";
gum confirm "Continue Work??" --default=false --affirmative "Next" --negative "Quit" || exit 0;
if command -v work-search; then
    work-search "$@";
fi
